# Generated by Django 3.2.9 on 2022-01-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=32, verbose_name='姓名：')),
                ('identity', models.IntegerField(choices=[(0, '正式教師'), (1, '行政人員'), (2, '代理教師'), (3, '兼任教師')], default=0, verbose_name='身分：')),
                ('level', models.IntegerField(choices=[(0, '國中部'), (1, '高中部')], default=0, verbose_name='國/高中部：')),
                ('teaching', models.CharField(max_length=30, verbose_name='科目：')),
                ('administration', models.CharField(max_length=30, verbose_name='職稱：')),
                ('tel', models.CharField(max_length=255, verbose_name='聯絡電話：')),
                ('email', models.EmailField(max_length=254, verbose_name='電子信箱：')),
                ('status', models.IntegerField(choices=[(0, '在職'), (1, '已離職')], default=0, verbose_name='狀態：')),
            ],
        ),
    ]
