# Generated by Django 3.2.9 on 2022-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='administration',
            field=models.CharField(max_length=30, verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='identity',
            field=models.IntegerField(choices=[(0, '正式教師'), (1, '行政人員'), (2, '代理教師'), (3, '兼任教師')], default=0, verbose_name='身分'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='level',
            field=models.IntegerField(choices=[(0, '國中部'), (1, '高中部')], default=0, verbose_name='國/高中部'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='realname',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='status',
            field=models.IntegerField(choices=[(0, '在職'), (1, '已離職')], default=0, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='teaching',
            field=models.CharField(max_length=30, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='聯絡電話'),
        ),
    ]
