# Generated by Django 3.2.9 on 2022-01-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='設備編號：')),
                ('property_number', models.CharField(max_length=255, verbose_name='財產編號：')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註：')),
                ('typo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type')),
            ],
        ),
    ]
