# Generated by Django 3.2.9 on 2022-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='number',
            field=models.CharField(max_length=255, verbose_name='設備編號'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='property_number',
            field=models.CharField(max_length=255, verbose_name='財產編號'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
    ]
