# Generated by Django 3.2.9 on 2022-01-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20220115_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='typo',
            new_name='type',
        ),
    ]
