# Generated by Django 3.2.9 on 2022-01-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_rename_type_equipment_typo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='typo',
        ),
    ]
