# Generated by Django 3.2.9 on 2022-01-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.DateTimeField(auto_now_add=True, verbose_name='借閱時間')),
                ('returned', models.DateTimeField(null=True, verbose_name='歸還時間')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('person_who_borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower')),
            ],
        ),
    ]
