# Generated by Django 3.2.9 on 2022-01-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo', models.CharField(max_length=25, verbose_name='型號：')),
                ('buy_time', models.DateField()),
                ('detailed', models.TextField(max_length=25, verbose_name='詳細規格：')),
                ('status', models.IntegerField(choices=[(0, '使用中'), (1, '已報廢除帳')], default=0, verbose_name='狀態：')),
            ],
        ),
    ]
