# Generated by Django 3.2.9 on 2022-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='typo',
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.CharField(default=True, max_length=25, verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='type',
            name='buy_time',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='detailed',
            field=models.TextField(default=True, max_length=25, verbose_name='詳細規格'),
        ),
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.IntegerField(choices=[(0, '使用中'), (1, '已報廢除帳')], default=0, verbose_name='狀態'),
        ),
    ]
