# Generated by Django 3.2.9 on 2022-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_auto_20220115_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='buy_time',
            field=models.DateField(default=''),
        ),
    ]
